springdoc:
  api-docs:
    path: /v3/api-docs   # Customize the path where the OpenAPI JSON is served
    enabled: true
  swagger-ui:
    path: /swagger-ui # Customize the path where Swagger UI is accessible
  group-configs:
    - group: 'account'
      paths-to-match: "/api/accounts/** " # Only match endpoints with /accounts/
      packages-to-scan: com.skyflytech.accountservice.controller  # Only scan this package for API endpoints
    - group: 'transaction'
      paths-to-match: "/api/transactions/** " # Only match endpoints with /transactions/
      packages-to-scan: com.skyflytech.accountservice.controller  # Only scan this package for API endpoints
    - group: 'journalEntry'
      paths-to-match: "/api/journalEntries/** " # Only match endpoints with /transactions/
      packages-to-scan: com.skyflytech.accountservice.controller  # Only scan this package for API endpoints

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn